pipeline {
	agent {
        label 'KST-AGENT'
    }
    options{
        timeout(time: '30', UNIT: 'MINUTES')
        disableConcurrentBuilds()
    }
	stages {
		stage('GIT CLONE'){
			steps{
				script{
				sh """
					uname -a
					echo "THIS IS A SAMPLE"
				"""
				}
			}
		}
	}
	post {
		always {
			echo "job executed"
            deleteDir()
		}
		failure {
			echo "job failed"
		}
		success {
			echo "job Success"
		}
	}
}
	
	