pipeline {
	agent any
	stages {
		stage('GIT CLONE'){
			steps{
				script{
				sh """
					uname -a
					echo "THIS IS A SAMPLE"
				"""
				}
			}
		}
	}
	post {
		always {
			echo "job executed"
		}
		failure {
			echo "job failed"
		}
		success {
			echo "job Success"
		}
	}
}
	
	