pipeline{
    agent{
        label 'KST-AGENT'
    }
    environment {
        APP_VERSION = ''
        REGION =  'us-east-1'
        ACC_ID = '291293118913'
        PROJECT = 'KST'
        COMPONENT = 'catalogue'
    } 
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }  
    stages {
        stage('Read package.json') {
            steps {
                script {
                    def packageJson = readJSON file: 'kst/package.json'
                    APP_VERSION = packageJson.version
                    echo "Package version: ${APP_VERSION}"
                }
            }
        }
        stage('check packages'){
            steps{
                script{
                    sh """
                        npm -v
                        node -v
                    """
                }
            }
        }
        stage('install Dependency'){
            steps{
                dir('kst'){
                    sh """
                        npm install
                    """
                }
            }
        }
        stage('unit testing'){
            steps{
                script{
                    echo 'unit testing'
                }
            }
        }
        stage('Build and Push'){
            steps{
                dir('kst'){
                    withAWS(credentials: 'aws-cred', region: 'us-east-1'){
                        sh """
                        aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com
                        docker build -t ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/${COMPONENT}:${APP_VERSION} .
                        docker push ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/${COMPONENT}:${APP_VERSION}
                        """
                    }
                }
            }
        }
    }
    post {
        always {
            echo "Job Executed"
        }
        failure {
            echo "Failed"
        }
        success {
            echo 'Job Success'
        }
    }
}